### ISSUE TITLE
comenatarios día 5

### ISSUE THREAD

**Issue by Julenasti** [DatSciR/ciencia_datos#8]
- https://github.com/DatSciR/ciencia_datos/blob/4d8fa7f1fefc404b6fc122da3c74170605d3bdb1/CADIC_2024/dia_5_comunicacion_colaboracion.qmd#L80 mira https://rstudio.github.io/reticulate/
- https://github.com/DatSciR/ciencia_datos/blob/4d8fa7f1fefc404b6fc122da3c74170605d3bdb1/CADIC_2024/dia_5_comunicacion_colaboracion.qmd#L113 te falta el .bib arriba. Cuando añades desde zotero te genera el .bib automáticamente. Eso mola!
- Aquí tienes un link que no funciona: https://github.com/DatSciR/ciencia_datos/blob/4d8fa7f1fefc404b6fc122da3c74170605d3bdb1/CADIC_2024/dia_5_comunicacion_colaboracion.qmd#L167 este sería el link correcto: https://quarto.org/docs/computations/execution-options.html
- para hacer el siguiente ejercicio esto lo tendrás que explicar un poco más: https://github.com/DatSciR/ciencia_datos/blob/4d8fa7f1fefc404b6fc122da3c74170605d3bdb1/CADIC_2024/dia_5_comunicacion_colaboracion.qmd#L245 puedes añadir este link donde se explica: https://quarto.org/docs/output-formats/ms-word-templates.html o este link que tienes ahora en las refs lo tienes explicado muy bien: https://www.infoworld.com/article/3671668/how-to-create-word-docs-from-r-or-python-with-quarto.html
- creo que me dijiste que git y github lo explicabas el primer día así que me parece guay cómo lo has esctructurado. Ya me dirás qué tal la experiencia!
- el cuello de botella de todo esto es cuando los coautores te hacen comentarios en word y los quieres incluir en tu qmd. Si te lo preguntan yo he utilizado este paquete para eso: https://claudiozandonella.github.io/trackdown/articles/trackdown-workflow.html
Pero es café para muy cafeteros!

**Comment by VeruGHub** [comment]
¡Mil gracias Julen!
